### ISSUE TITLE
`watchdog` package is missing from requirements.txt

### ISSUE THREAD

**Issue by shymega** [vktec/vsg#10]
The `watchdog` package is missing from `requirements.txt` for vsg. This needs to be added so users can run the `./build.py` script - it **refuses** to run otherwise.

```
> ./build.py build
Traceback (most recent call last):
  File "./build.py", line 35, in <module>
    from watchdog.observers import Observer
ModuleNotFoundError: No module named 'watchdog'
```

**Comment by vktec** [comment]
Oops, I must have forgotten to add it when I added that functionality. Good catch.
