### ISSUE TITLE
Consider switching to markdown.extensions.meta instead of python-frontmatter

### ISSUE THREAD

**Issue by vktec** [vktec/vsg#4]
Using the `meta` extension rather than `python-frontmatter` would cut the number of dependencies in half (`python-frontmatter` also depends on `six` and `PyYAML`), but the syntax is a bit less flexible.

Nested fields (which are translated to Python `dict`s) are straight up impossible using `meta`, but are easy using YAML:

```yaml
one:
  two: three
  four: five
```

Lists are still possible to create, but the syntax is a bit odd. Compare YAML:

```yaml
one:
  - two
  - three
  - four
```

to `meta` syntax:

```yaml
one: two
one: three
one: four
```

Still usable, but not pretty and rather counterintuitive.

In any case, I'll use this issue to document any other thoughts I have on this, and anyone else is welcome to participate too.

**Comment by shymega** [comment]
I'd prefer YAML syntax to `meta`'s syntax, personally. Feels more intuitive to me.

**Comment by shymega** [comment]
Besides, is it *really* worth switching to _another_ front matter lib under the reasoning of "we could bring down our deps!" - it seems like a very futile reason for changing something that already WORKS and IS intuitive.

**Comment by vktec** [comment]
Yeah, my thoughts exactly. I don't think it's worth it.
